import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

/** Generates a local, visibly prototype-stamped PDF export. */
export async function generateExportPdf({ records, includeSourceRefs, rangeLabel }) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage([612, 792]); // US Letter
  let y = 750;
  const marginX = 50;
  const lineHeight = 16;

  const drawText = (text, { size = 11, bold = false, color = rgb(0.02, 0.08, 0.18) } = {}) => {
    if (y < 60) {
      page = pdfDoc.addPage([612, 792]);
      y = 750;
    }
    page.drawText(text, { x: marginX, y, size, font: bold ? boldFont : font, color });
    y -= lineHeight;
  };

  // Mandatory prototype stamp is not user-removable.
  drawText("PROTOTYPE EXPORT — NOT PASSWORD PROTECTED", { size: 13, bold: true, color: rgb(0.7, 0.35, 0.05) });
  drawText("Generated by HEALTHNOTE prototype (application password protection not enabled).", { size: 9 });
  y -= 8;

  drawText("HEALTHNOTE — Health Record Export", { size: 16, bold: true });
  drawText(`Range: ${rangeLabel || "Current / latest information"}`, { size: 10 });
  drawText(`Generated: ${new Date().toISOString()}`, { size: 10 });
  y -= 10;

  for (const record of records) {
    drawText(`${record.fieldLabel}`, { bold: true, size: 12 });
    drawText(`${record.value} ${record.unit || ""}  —  ${record.verificationState}${record.isBaseline ? " · BASELINE" : ""}`);
    drawText(`${record.dateProvenance?.label || "Undated"}: ${record.dateProvenance?.value || "—"}`);
    drawText(`Control #: ${record.controlNumberFormatted}`);
    if (includeSourceRefs) {
      drawText(`Source: ${record.sourceType}`);
    }
    y -= 6;
  }

  const bytes = await pdfDoc.save();
  return new Blob([bytes], { type: "application/pdf" });
}
