import { getDb, CANONICAL_FIELDS } from "../data/db.js";
import { isFirstSaveForField } from "./chronology.js";
import { nextControlNumber, formatControlNumber } from "./controlNumber.js";

function fieldWasEdited(field){if(field.userEdited)return true;const hv=Object.prototype.hasOwnProperty.call(field,"originalExtractedValue"),hu=Object.prototype.hasOwnProperty.call(field,"originalExtractedUnit");return(hv&&Number(field.value)!==Number(field.originalExtractedValue))||(hu&&String(field.unit??"").trim()!==String(field.originalExtractedUnit??"").trim());}
export async function saveConfirmedCapture({sourceType,sourceInstitution,captureOrigin,clinicalDate,documentPrintAt,rawOcrText,confirmedFields,sourceRef,sourceBlob,observedAt:suppliedObservedAt}){
 const db=await getDb(),meta=(await db.get("prototypeArchive","local-archive"))||{},controlNumber=nextControlNumber(meta.highestControlNumberIssued||0),sourceDocumentId=crypto.randomUUID(),now=new Date().toISOString(),isCamera=captureOrigin==="camera",isManual=captureOrigin==="manual",observedAt=!clinicalDate&&isCamera?(suppliedObservedAt||now):null,hasOriginal=Boolean(sourceBlob&&typeof sourceBlob.size==="number"&&sourceBlob.type),sourceVerificationState=!isManual&&(hasOriginal||Boolean(observedAt))?"VERIFIED":"UNVERIFIED",anyEdited=confirmedFields.some(fieldWasEdited);
 const sourceDocument={id:sourceDocumentId,controlNumber,controlNumberFormatted:formatControlNumber(controlNumber),sourceType,sourceInstitution:sourceInstitution||null,captureOrigin,sourceRef:sourceRef||null,sourceBlob:sourceBlob||null,sourceMimeType:sourceBlob?.type||null,rawOcrText:rawOcrText||"",clinicalDate:clinicalDate||null,documentPrintAt:documentPrintAt||null,observedAt,addedAt:now,verificationState:anyEdited?"UNVERIFIED":sourceVerificationState,createdAt:now,updatedAt:now};
 const observations=[];
 for(const field of confirmedFields){const canonical=CANONICAL_FIELDS.find(f=>f.id===field.canonicalFieldId);if(!canonical)continue;const existing=await db.getAllFromIndex("observation","canonicalFieldId",field.canonicalFieldId),tombstone=await db.get("baselineTombstone",field.canonicalFieldId),wasEdited=fieldWasEdited(field);observations.push({id:crypto.randomUUID(),sourceDocumentId,canonicalFieldId:field.canonicalFieldId,rawLabel:field.rawLabel,normalizedLabel:canonical.label,value:Number(field.value),unit:String(field.unit||"").trim(),referenceRange:field.referenceRange||null,verificationState:isManual||wasEdited?"UNVERIFIED":sourceVerificationState,isBaseline:isFirstSaveForField(existing,tombstone),clinicalDate:clinicalDate||null,observedAt,addedAt:now,sourceType,sourceInstitution:sourceInstitution||null,controlNumber,controlNumberFormatted:formatControlNumber(controlNumber),createdAt:now,updatedAt:now,correctionHistory:[],userEditedFromSource:wasEdited,originalExtractedValue:Object.prototype.hasOwnProperty.call(field,"originalExtractedValue")?field.originalExtractedValue:null,originalExtractedUnit:Object.prototype.hasOwnProperty.call(field,"originalExtractedUnit")?field.originalExtractedUnit:null,ocrAgreement:field.ocrAgreement||null,unitOcrAgreement:field.unitOcrAgreement||null});}
 const tx=db.transaction(["sourceDocument","observation","prototypeArchive"],"readwrite");await tx.objectStore("sourceDocument").put(sourceDocument);for(const obs of observations)await tx.objectStore("observation").put(obs);await tx.objectStore("prototypeArchive").put({...meta,id:"local-archive",highestControlNumberIssued:controlNumber});await tx.done;return{sourceDocument,observations};
}
export async function correctObservation(observationId,{newValue,newUnit,reason}){const db=await getDb(),obs=await db.get("observation",observationId);if(!obs)throw new Error(`Observation ${observationId} not found`);const auditEntry={id:crypto.randomUUID(),observationId,previousValue:obs.value,previousUnit:obs.unit,newValue,newUnit,reason:reason||null,correctedAt:new Date().toISOString()},updatedObs={...obs,value:newValue,unit:newUnit,verificationState:"UNVERIFIED",userEditedFromSource:true,updatedAt:auditEntry.correctedAt,correctionHistory:[...(obs.correctionHistory||[]),auditEntry.id]},tx=db.transaction(["observation","correctionAudit"],"readwrite");await tx.objectStore("observation").put(updatedObs);await tx.objectStore("correctionAudit").put(auditEntry);await tx.done;return{observation:updatedObs,auditEntry};}
export async function deleteSourceDocument(sourceDocumentId){const db=await getDb(),observations=await db.getAllFromIndex("observation","sourceDocumentId",sourceDocumentId),tx=db.transaction(["sourceDocument","observation","baselineTombstone"],"readwrite");for(const obs of observations){if(obs.isBaseline)await tx.objectStore("baselineTombstone").put({canonicalFieldId:obs.canonicalFieldId,originalBaselineObservationId:obs.id,originalBaselineSourceDocumentId:sourceDocumentId,originalBaselineValue:obs.value,originalBaselineDate:obs.clinicalDate,deletedAt:new Date().toISOString(),note:"Baseline source was deleted. No replacement baseline was auto-assigned."});await tx.objectStore("observation").delete(obs.id);}await tx.objectStore("sourceDocument").delete(sourceDocumentId);await tx.done;}
