import React, { useState, useRef, useCallback } from "react";
import { SourceCameraIcon, FileIcon } from "../components/icons/index.js";
import { CANONICAL_FIELDS } from "../data/db.js";
import { extractCandidateFields, mergeCandidatePasses, extractDates, computeReviewFlags } from "../lib/fieldParser.js";
import { buildOcrVariants } from "../lib/ocrPreprocess.js";
import { saveConfirmedCapture } from "../lib/saveFlow.js";

const STEPS = { CHOOSE:"choose", PDF_PAGE_SELECT:"pdf_page_select", PREVIEW:"preview", OCR_RUNNING:"ocr_running", REVIEW:"review", MANUAL:"manual", SAVING:"saving" };
export default function CaptureScreen({ onSaved, onBack }) {
  const [step,setStep]=useState(STEPS.CHOOSE), [file,setFile]=useState(null), [captureOrigin,setCaptureOrigin]=useState(null), [previewUrl,setPreviewUrl]=useState(null), [pdfPages,setPdfPages]=useState([]), [selectedPageNumber,setSelectedPageNumber]=useState(null), [ocrProgress,setOcrProgress]=useState(0), [ocrError,setOcrError]=useState(null), [rawOcrText,setRawOcrText]=useState(""), [candidateFields,setCandidateFields]=useState([]), [dates,setDates]=useState({clinicalDate:null,printDate:null}), [reviewFlags,setReviewFlags]=useState([]), [manualField,setManualField]=useState({canonicalFieldId:CANONICAL_FIELDS[0].id,value:"",unit:"",clinicalDate:""});
  const fileInputRef=useRef(null), cameraInputRef=useRef(null);
  const resetToChoose=()=>{setStep(STEPS.CHOOSE);setFile(null);setCaptureOrigin(null);setPreviewUrl(null);setPdfPages([]);setSelectedPageNumber(null);setOcrProgress(0);setOcrError(null);setRawOcrText("");setCandidateFields([]);setDates({clinicalDate:null,printDate:null});setReviewFlags([]);};
  const handleFileChosen=useCallback(async(chosenFile,origin)=>{setFile(chosenFile);setCaptureOrigin(origin);if(chosenFile.type==="application/pdf"){setStep(STEPS.PDF_PAGE_SELECT);await renderPdfThumbnails(chosenFile);}else{setPreviewUrl(URL.createObjectURL(chosenFile));setStep(STEPS.PREVIEW);}},[]);
  const renderPdfThumbnails=async(pdfFile)=>{const pdfjsLib=await import("pdfjs-dist");const workerSrc=(await import("pdfjs-dist/build/pdf.worker.mjs?url")).default;pdfjsLib.GlobalWorkerOptions.workerSrc=workerSrc;const pdf=await pdfjsLib.getDocument({data:await pdfFile.arrayBuffer()}).promise;const pages=[];for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const page=await pdf.getPage(pageNumber),viewport=page.getViewport({scale:.4}),canvas=document.createElement("canvas");canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext("2d"),viewport}).promise;pages.push({pageNumber,thumbnailDataUrl:canvas.toDataURL()});}setPdfPages(pages);};
  const handlePageSelected=async(pageNumber)=>{setSelectedPageNumber(pageNumber);const pdfjsLib=await import("pdfjs-dist"),pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,page=await pdf.getPage(pageNumber),viewport=page.getViewport({scale:3}),canvas=document.createElement("canvas");canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext("2d"),viewport}).promise;setPreviewUrl(canvas.toDataURL("image/png"));setStep(STEPS.PREVIEW);};
  const runOcr=async()=>{setStep(STEPS.OCR_RUNNING);setOcrError(null);setOcrProgress(0);try{const Tesseract=await import("tesseract.js"),localBase=import.meta.env.BASE_URL,variants=await buildOcrVariants(previewUrl),passes=[],texts=[];for(let i=0;i<variants.length;i++){const variant=variants[i];const {data}=await Tesseract.recognize(variant.image,"eng",{workerPath:`${localBase}ocr/worker.min.js`,corePath:`${localBase}ocr/core`,langPath:`${localBase}ocr/lang`,workerBlobURL:false,logger:(m)=>{if(m.status==="recognizing text")setOcrProgress(Math.round(((i+m.progress)/variants.length)*100));}});const text=data.text||"";texts.push(`=== OCR PASS ${i+1}: ${variant.label} ===\n${text}`);passes.push(extractCandidateFields(text).map(c=>({...c,ocrPassId:variant.id})));}const candidates=mergeCandidatePasses(...passes).map(c=>({...c,originalExtractedValue:c.value,originalExtractedUnit:c.unit||"",userEdited:false}));const combinedText=texts.join("\n\n"),extractedDates=extractDates(combinedText);setRawOcrText(combinedText);setCandidateFields(candidates);setDates(extractedDates);setReviewFlags(computeReviewFlags(candidates,extractedDates));setStep(STEPS.REVIEW);}catch(err){setOcrError(err.message||"OCR failed. You can retry or go back.");setStep(STEPS.PREVIEW);}};
  const updateCandidateValue=(id,key,value)=>setCandidateFields(prev=>prev.map(c=>{if(c.canonicalFieldId!==id)return c;const updated={...c,[key]:value};return{...updated,userEdited:Number(updated.value)!==Number(updated.originalExtractedValue)||String(updated.unit||"").trim()!==String(updated.originalExtractedUnit||"").trim()};}));
  const handleConfirmSave=async()=>{setStep(STEPS.SAVING);const{sourceDocument}=await saveConfirmedCapture({sourceType:file?.type==="application/pdf"?"Lab report (PDF)":"Lab report (photo)",captureOrigin,clinicalDate:dates.clinicalDate,documentPrintAt:dates.printDate,rawOcrText,confirmedFields:candidateFields,sourceRef:file?.name||"capture",sourceBlob:file});onSaved(sourceDocument.id);};
  const handleManualSave=async()=>{const numericValue=Number(manualField.value);if(!Number.isFinite(numericValue))return;setStep(STEPS.SAVING);const canonical=CANONICAL_FIELDS.find(f=>f.id===manualField.canonicalFieldId),{sourceDocument}=await saveConfirmedCapture({sourceType:"Manual entry",captureOrigin:"manual",clinicalDate:manualField.clinicalDate||null,documentPrintAt:null,rawOcrText:"",confirmedFields:[{canonicalFieldId:manualField.canonicalFieldId,rawLabel:canonical?.label||manualField.canonicalFieldId,value:numericValue,unit:manualField.unit.trim(),userEdited:true}],sourceRef:null,sourceBlob:null});onSaved(sourceDocument.id);};
  return <div className="hn-capture-screen"><header className="hn-screen-header"><button type="button" onClick={onBack} aria-label="Back">←</button><h2>Capture</h2></header>
    {step===STEPS.CHOOSE&&<div className="hn-capture-choose"><p>Choose how to add a lab report.</p><button type="button" className="hn-btn hn-btn-primary" onClick={()=>cameraInputRef.current?.click()}><SourceCameraIcon className="hn-btn-icon"/>Use Camera</button><button type="button" className="hn-btn hn-btn-outline" onClick={()=>fileInputRef.current?.click()}><FileIcon className="hn-btn-icon"/>Upload Image or PDF</button><button type="button" className="hn-btn hn-btn-outline" onClick={()=>setStep(STEPS.MANUAL)}>Enter Manually</button><input ref={cameraInputRef} type="file" accept="image/*" capture="environment" hidden onChange={e=>e.target.files[0]&&handleFileChosen(e.target.files[0],"camera")}/><input ref={fileInputRef} type="file" accept="image/*,application/pdf" hidden onChange={e=>e.target.files[0]&&handleFileChosen(e.target.files[0],"upload")}/></div>}
    {step===STEPS.MANUAL&&<div className="hn-manual-entry" data-testid="manual-entry-form"><p>Manual entries remain permanently marked UNVERIFIED unless an original source is attached in a separate record.</p><label>Health field<select value={manualField.canonicalFieldId} onChange={e=>setManualField(v=>({...v,canonicalFieldId:e.target.value}))}>{CANONICAL_FIELDS.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label><label>Value<input type="number" step="any" value={manualField.value} onChange={e=>setManualField(v=>({...v,value:e.target.value}))}/></label><label>Unit<input type="text" value={manualField.unit} onChange={e=>setManualField(v=>({...v,unit:e.target.value}))}/></label><label>Clinical date (optional)<input type="date" value={manualField.clinicalDate} onChange={e=>setManualField(v=>({...v,clinicalDate:e.target.value}))}/></label><button type="button" className="hn-btn hn-btn-primary" disabled={!manualField.value} onClick={handleManualSave}>Save UNVERIFIED Entry</button><button type="button" className="hn-link-button" onClick={resetToChoose}>Cancel</button></div>}
    {step===STEPS.PDF_PAGE_SELECT&&<div className="hn-pdf-page-select"><p>Select the page containing the CBC results.</p>{pdfPages.length===0&&<p className="hn-empty-state">Rendering page thumbnails…</p>}<div className="hn-pdf-page-grid">{pdfPages.map(p=><button key={p.pageNumber} type="button" onClick={()=>handlePageSelected(p.pageNumber)}><img src={p.thumbnailDataUrl} alt={`Page ${p.pageNumber}`}/><span>Page {p.pageNumber}</span></button>)}</div></div>}
    {step===STEPS.PREVIEW&&<div className="hn-capture-preview"><img src={previewUrl} alt="Selected source preview" className="hn-preview-image"/>{ocrError&&<p className="hn-error-text">{ocrError}</p>}<button type="button" className="hn-btn hn-btn-primary" onClick={runOcr}>{ocrError?"Retry OCR":"Run OCR"}</button><button type="button" className="hn-link-button" onClick={resetToChoose}>Choose a different source</button></div>}
    {step===STEPS.OCR_RUNNING&&<div className="hn-capture-ocr-progress"><p>Reading document locally with 3 OCR passes… {ocrProgress}%</p><div className="hn-progress-bar"><div className="hn-progress-bar-fill" style={{width:`${ocrProgress}%`}}/></div></div>}
    {step===STEPS.REVIEW&&<ReviewTable candidateFields={candidateFields} dates={dates} reviewFlags={reviewFlags} rawOcrText={rawOcrText} captureOrigin={captureOrigin} onUpdateDate={value=>setDates(v=>({...v,clinicalDate:value||null}))} onUpdateField={updateCandidateValue} onConfirm={handleConfirmSave}/>} {step===STEPS.SAVING&&<p>Saving…</p>}</div>;
}
function ReviewTable({candidateFields,dates,reviewFlags,rawOcrText,captureOrigin,onUpdateDate,onUpdateField,onConfirm}){return <div className="hn-review-table"><label className="hn-review-date">Clinical date (optional)<input type="date" value={dates.clinicalDate||""} onChange={e=>onUpdateDate(e.target.value)}/></label>{!dates.clinicalDate&&captureOrigin==="camera"&&<p className="hn-explainer">No document date detected. The device capture time will be stored as the system-generated observation time.</p>}{!dates.clinicalDate&&captureOrigin==="upload"&&<p className="hn-explainer">No document date detected. This upload will remain undated; upload time is provenance only.</p>}{reviewFlags.length>0&&<ul className="hn-review-flags">{reviewFlags.map((f,i)=><li key={i} className={`hn-flag hn-flag-${f.type}`}>{f.message}</li>)}</ul>}{candidateFields.length===0&&<p className="hn-empty-state">OCR could not find any of the eight supported fields on this page.</p>}{candidateFields.map(c=>{const canonical=CANONICAL_FIELDS.find(f=>f.id===c.canonicalFieldId);return <div key={c.canonicalFieldId} className={`hn-review-row ${c.userEdited?"hn-review-row-edited":""}`}><label>{canonical?.shortLabel||c.rawLabel}</label><input type="number" step="any" value={c.value} onChange={e=>onUpdateField(c.canonicalFieldId,"value",parseFloat(e.target.value))}/><input type="text" value={c.unit||""} onChange={e=>onUpdateField(c.canonicalFieldId,"unit",e.target.value)} placeholder="unit"/>{c.referenceRange&&<span className="hn-review-range">Ref: {c.referenceRange.low}–{c.referenceRange.high}</span>}<span className="hn-ocr-pass-note">OCR agreement: {c.ocrAgreement||1}/3</span>{c.userEdited&&<span className="hn-edit-provenance">Edited from OCR {c.originalExtractedValue}{c.originalExtractedUnit?` ${c.originalExtractedUnit}`:""} · saves UNVERIFIED</span>}</div>})}<details className="hn-raw-ocr-text"><summary>Raw OCR text (all passes)</summary><pre>{rawOcrText}</pre></details><button type="button" className="hn-btn hn-btn-primary" disabled={candidateFields.length===0} onClick={onConfirm} data-testid="confirm-save">Confirm and Save</button></div>;}
